export const Component = {
    RestApplication: Symbol.for('RestApplication'),
    Logger: Symbol.for('Logger'),
    Config: Symbol.for('Config'),
    DatabaseClient: Symbol.for('DatabaseClient'),
    UserService: Symbol.for('UserService'),
    UserModel:Symbol.for('UserModel'),
    UserController:Symbol.for('UserController'),
    ExceptionFilter:Symbol.for('ExceptionFilter'),
    BreakModel:Symbol.for('BreakModel'),
    BreakService:Symbol.for('BreakService'),
    BreakController:Symbol.for('BreakController'),
    MachineModel:Symbol.for('MachineModel'),
    MachineService:Symbol.for('MachineService'),
    MachineController:Symbol.for('MachineController'),
    BreakTypeByMachineModel:Symbol.for('BreakTypeByMachineModel'),
    BreakTypeByMachineService:Symbol.for('BreakTypeByMachineService'),
    BreakTypeByMachineController:Symbol.for('BreakTypeByMachineController'),
    AuthService:Symbol.for('AuthService'),
    AuthExceptionFilter:Symbol.for('AuthExceptionFilter'),
} as const;